### ISSUE TITLE
language on homepage links to homepage 

### ISSUE THREAD

**Issue by gbinal** [18F/fbopen#168]
On http://18f.github.io/fbopen/, the second sections says ` Visit our API documentation at 18f.github.io/fbopen`, which links to the same page.

**Comment by arowla** [comment]
@gbinal not seeing this...? It links to http://18f.github.io/fbopen/apidocs/ for me.

**Comment by gbinal** [comment]
Strange.  I just double checked and when I'm on that page, the link in that sentence goes to https://18f.github.io/fbopen/ for me.  

![screen shot 2015-01-29 at 12 41 05 pm](https://cloud.githubusercontent.com/assets/633088/5962771/302b9608-a7b4-11e4-9888-d19414a46302.png)

**Comment by arowla** [comment]
Ah! I misunderstood where you were pointing to. I see it now. Thanks!

On Thu, Jan 29, 2015 at 12:41 PM, Gray Brooks <notifications@github.com>
wrote:

> Strange. I just double checked and when I'm on that page, the link in that
> sentence goes to https://18f.github.io/fbopen/ for me.
>
> [image: screen shot 2015-01-29 at 12 41 05 pm]
> <https://cloud.githubusercontent.com/assets/633088/5962771/302b9608-a7b4-11e4-9888-d19414a46302.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/fbopen/issues/168#issuecomment-72069369>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by arowla** [comment]
Fixed in 3f9d32f68d9ccd9d837b152259422b6afd0d819a
