### ISSUE TITLE
Updated Data not available through API

### ISSUE THREAD

**Issue by sanketkh** [18F/fbopen#176]
Hello,

We are using the FBOpen API, but we came to an use case where when we try to get FBO data for a solicitation number using the API, we dont get the updated data as seen in FBO site(http://www.fbo.gov).

Please can you suggest us if there is a way to retrieve the updated data using the API.

Thanks,
Sanket

**Comment by arowla** [comment]
What is the solicitation number you are looking for?

**Comment by sanketkh** [comment]
Solicitation Number is SPE4A615TCH54
https://www.fbo.gov/index?s=opportunity&mode=form&id=6b62fde2ec1ff264a71b0e377c0d99b0&tab=core&_cview=1

**Comment by arowla** [comment]
This is available here:

http://api.data.gov/gsa/fbopen/v0/opps?q=solnbr:SPE4A615TCH54&api_key=DEMO_KEY&show_closed=true

FBOpen does not show closed solicitations by default, so the `show_closed=true` query parameter is necessary to see this record.

**Comment by sanketkh** [comment]
We are using the show_closed=true query parameter and also we are getting the data, but as I had mentioned earlier that we are not able to get updated/modified data for the solicitation number.
For example the "notice_type" received from API for this solicitation number is "COMBINE" whereas its been updated/modified to "Award" in the (www.fbo.gov) site. Also contact information does not seem to be updated in API response.

**Comment by arowla** [comment]
FBOpen does not load AWARD mods. So for this record we only load the original COMBINE record.

**Comment by sanketkh** [comment]
Ok, Got it !!!! Thanks !!!!
