### ISSUE TITLE
Why is this deprecated?

### ISSUE THREAD

**Issue by frozegnome** [18F/fbopen#199]
I am curious as to why this package was deprecated. Also, I am wondering if there are any alternatives that 18F recommends considering this deprecation.

Any insight would help.

**Comment by kaitlin** [comment]
Hi @frozegnome, sorry for the delayed reply. We don't have the funding to continue development on this project, which is why it's deprecated. You may continue to use it of course, but it won't be actively developed. 

Best,
Kaitlin
